# Generated by Django 3.1.6 on 2021-02-03 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MovieEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MovieName', models.CharField(max_length=50)),
                ('MovieYear', models.IntegerField()),
                ('MovieStars', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'movie_entry',
            },
        ),
    ]
